// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pb/mediators.proto

package mediators

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeidateClient is the client API for Meidate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeidateClient interface {
	Meidate(ctx context.Context, in *MediationInput, opts ...grpc.CallOption) (*MediationOutput, error)
}

type meidateClient struct {
	cc grpc.ClientConnInterface
}

func NewMeidateClient(cc grpc.ClientConnInterface) MeidateClient {
	return &meidateClient{cc}
}

func (c *meidateClient) Meidate(ctx context.Context, in *MediationInput, opts ...grpc.CallOption) (*MediationOutput, error) {
	out := new(MediationOutput)
	err := c.cc.Invoke(ctx, "/Meidate/Meidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeidateServer is the server API for Meidate service.
// All implementations must embed UnimplementedMeidateServer
// for forward compatibility
type MeidateServer interface {
	Meidate(context.Context, *MediationInput) (*MediationOutput, error)
	mustEmbedUnimplementedMeidateServer()
}

// UnimplementedMeidateServer must be embedded to have forward compatible implementations.
type UnimplementedMeidateServer struct {
}

func (UnimplementedMeidateServer) Meidate(context.Context, *MediationInput) (*MediationOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meidate not implemented")
}
func (UnimplementedMeidateServer) mustEmbedUnimplementedMeidateServer() {}

// UnsafeMeidateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeidateServer will
// result in compilation errors.
type UnsafeMeidateServer interface {
	mustEmbedUnimplementedMeidateServer()
}

func RegisterMeidateServer(s grpc.ServiceRegistrar, srv MeidateServer) {
	s.RegisterService(&Meidate_ServiceDesc, srv)
}

func _Meidate_Meidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeidateServer).Meidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Meidate/Meidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeidateServer).Meidate(ctx, req.(*MediationInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Meidate_ServiceDesc is the grpc.ServiceDesc for Meidate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meidate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Meidate",
	HandlerType: (*MeidateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meidate",
			Handler:    _Meidate_Meidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/mediators.proto",
}
