name: Go

on:
  push:
    branches:
      - master
      - feature/***
  pull_request:
    branches:
      - master
      - feature/***

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test